export const IMAGE_READER = "IMAGE_READER";
export const VIDEO_READER = "VIDEO_READER";
export const READERS = { IMAGE_READER, VIDEO_READER };

export const HTML_RENDERER = "HTML_RENDERER";
export const CANVAS_RENDERER = "CANVAS_RENDERER";
export const RENDERERS = { HTML_RENDERER, CANVAS_RENDERER };


export const BRIGHTNESS_FILTER = "BRIGHTNESS_FILTER";
export const CONTRAST_FILTER = "CONTRAST_FILTER";
export const DESATURATE_FILTER = "DESATURATE_FILTER";
export const INVERSE_FILTER = "INVERSE_FILTER";
export const FILTERS = { BRIGHTNESS_FILTER, CONTRAST_FILTER, DESATURATE_FILTER, INVERSE_FILTER };
