export default "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAABCAYAAAAb4BS0AAAABmJLR0QA/wD/AP+gvaeTAAAACXB" +
    "IWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3wsPEwohqOnA4AAAABl0RVh0Q29tbWVudABDcmVhdGVkIHdpdGggR0lNUFeBDhcAAAAVSURBVAjXY" +
    "/jPwPCf4T/DfwaG//8BI+kF+5tmBi0AAAAASUVORK5CYII=";